apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project
  labels:
    app: the-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      containers:
      - name: the-project
        image: zorran/the-project:latest
        imagePullPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: the-project
  labels:
    app: the-project
spec:
  containers:
  - name: the-project
    image: zorran/the-project:latest
    env:
       - name: DYNAMO_USER
         valueFrom:
           secretKeyRef:
             name: dynamodb-seciruty
             key: amazon.aws.accesskey
       - name: DYNAMO_PASSWORD
         valueFrom:
           secretKeyRef:
             name: dynamodb-seciruty
             key: amazon.aws.secretkey
